version: '3.8'
services:
    app:
        image: node:latest
        container_name: optimonk-secret-app
        build: .
        command: npm run start
        ports:
            - "3000:3000"
        environment:
            HOST: 0.0.0.0
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_DATABASE: secret-db
        ports:
            - 27017:27017